                                                                                                                                                                                                                                                                
---
- name: Tuesday Challenge
  hosts: localhost
  connection: network_cli
  gather_facts: no

  tasks:
   -name: creating a file
     copy:
        dest: challenge/challengefile.txt
       contents: "Success!"
       
   - name: create a directory
     file: 
       dest: challenge
       state: directry
