---
- name: Wednesday Warmup
  hosts: redfish
  connection: local
  gather_facts: false

  tasks:
  - name: Get CPU model
    community.general.redfish_info:
      category: Systems
      command: GetCpuInventory
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"  
      password: "{{ password }}"  
    register: cpuInv

  - name: Display CPU data
    debug:
      var: cpuInv

  - name: Restart system power gracefully
    community.general.redfish_command:
      category: Systems
      command: PowerGracefulRestart
      resource_id: BMC
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"   
      password: "{{ password }}" 
