---
- name: Send an HTTP GET to RedFish endpoint
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:

  - name: Send an HTTP GET to SessionService
    uri:
      url: http://127.0.0.1:2224/redfish/v1/SessionService
    register: SessionServiceResponse
  
  - name: "Output response"
    debug:
      var: SessionServiceResponse

